name: nrd

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 359

    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nrd/master/Files/ngrok.exe -OutFile ngrok.exe
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nrd/master/Files/nssm.exe -OutFile nssm.exe
    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy nssm.exe C:\Windows\System32
        copy ngrok.exe C:\Windows\System32
    - name: Connect your NGROK account
      run: .\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nrd/master/Files/nus.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nrd/master/Files/nchk.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nrd/master/Files/lp.bat -OutFile loop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nrd/master/Files/lop.bat -OutFile lop.bat
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nrd/master/Files/install_winrar.bat -OutFile install_winrar.bat
        Invoke-WebRequest https://raw.githubusercontent.com/hash243/nrd/master/Files/install_jd.bat -OutFile install_jd.bat
    - name: Installing WinRAR
      run: start install_winrar.bat
    - name: Installing Jd2
      run: start install_jd.bat
    - name: Installing ffmpeg
      run: choco install --no-progress ffmpeg
    - name: Installing streamlink
      run: choco install --no-progress streamlink
    - name: Installing youtube-dl
      run: choco install --no-progress youtube-dl
    - name: Installing http-server
      run: npm install --global http-server
    - name: Make YML file for NGROK.
      run: start NGROK-US.bat
    - name: Enable RDP Access.
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Create Tunnel
      run: sc start ngrok
    - name: Connect to your RDP 2core-7GB Ram.
      run: cmd /c NGROK-CHECK.bat
    - name: First Wait 5:59.
      run: cmd /c lop.bat
    - name: Second Wait for 5:59.
      run: cmd /c lop.bat
